[from-internal]
exten => 6001,1,Dial(PJSIP/6001)
exten => 6001,n,Hangup()

exten => 6002,1,Dial(PJSIP/6002)
exten => 6002,n,Hangup()

; Menu SVI
exten => 800,1,Answer()
exten => 800,n,Wait(1)
exten => 800,n,Background(dir-welcome)
exten => 800,n,WaitExten(5)

exten => 1,1,Dial(PJSIP/6001,20)
exten => 2,1,Dial(PJSIP/6002,20)

exten => i,1,Playback(pbx-invalid)
exten => i,n,Goto(800,3)

exten => t,1,Playback(vm-goodbye)
exten => t,n,Hangup()
