[udp-transport]
type=transport
protocol=udp
bind=0.0.0.0

[tls-transport]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.pem
priv_key_file=/etc/asterisk/keys/asterisk.key
method=tlsv1_2

[6001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=6001-auth
aors=6001
media_encryption=sdes
transport=tls-transport

[6001-auth]
type=auth
auth_type=password
password=
username=6001

[6001]
type=aor
max_contacts=1

[6002]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=6002-auth
aors=6002
media_encryption=sdes
transport=tls-transport

[6002-auth]
type=auth
auth_type=password
password=
username=6002

[6002]
type=aor
max_contacts=1
